---
namespace: pokerops
name: r2
version: 0.0.1
readme: "README.md"
authors:
  - Carlos Gonzalez <43476850+carlosgo13@users.noreply.github.com>
description: Cloudflare R2 collection
license:
  - MIT
tags:
  - cloudflare
  - r2
dependencies:
  "nephelaiio.plugins": "*"
repository: http://github.com/pokerops/ansible-collection-r2
documentation: http://github.com/pokerops/ansible-collection-r2
homepage: http://github.com/pokerops/ansible-collection-r2
issues: http://github.com/pokerops/ansible-collection-r2/issues
build_ignore:
  - .devbox
  - .venv
  - ansible_collections
  - .ansible
  - .git
