---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: r2-${MOLECULE_SCENARIO_NAME}-01
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - r2
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      allow_world_readable_tmpfiles: true
      callbacks_enabled: ansible.posix.profile_tasks
  playbooks:
    prepare: ../common/prepare.yml
  inventory:
    group_vars:
      all:
        r2_buckets:
          - name: molecule_custom
            custom_domains:
              - name: molecule.wpnops.dev
          - name: molecule_private
          - name: molecule_public
            public: true
verifier:
  name: ansible
