---
- name: Get r2 objects
  hosts: "localhost"
  vars_files:
    - ../../playbooks/vars/main.yml
  tasks:
    - name: Get r2 objects
      amazon.aws.s3_object_info:
        access_key: "{{ _r2_access_key_id }}"
        region: "{{ _r2_region }}"
        secret_key: "{{ _r2_secret_access_key }}"
        endpoint_url: "{{ r2_endpoint_url }}"
        bucket_name: "{{ _bucket_name }}"
      vars:
        _buckets_state: "{{ r2_buckets | selectattr('state', 'defined') }}"
        _buckets_absent: "{{ _buckets_state | rejectattr('state', 'equalto', 'absent') }}"
        _bucket_names_absent: "{{ _buckets_absent }}"
        _buckets: "{{ r2_buckets | rejectattr('name', 'in', _bucket_names_absent) }}"
        _bucket_name: "{{ item.name }}"
      register: _r2_objects_query
      loop_control:
        label: "{{ _bucket_name }}"
      loop: "{{ _buckets }}"

    - name: Set r2 object facts
      ansible.builtin.set_fact:
        _r2_existing_paths: "{{ _objects | map(_dirname) | unique }}"
        _r2_existing_objects: "{{ _objects | map(_basename) }}"
        _r2_target_objects: "{{ _target_objects | map(_basename) }}"
        _r2_target_paths: "{{ _target_paths_overwritten }}"
      vars:
        _default:
          delete: false
        _target_objects: "{{ hostvars['localhost']['_r2_sync_temp_path'] }}"
        _target_paths: "{{ _r2_buckets | map(attribute='bucket_paths') | flatten }}"
        _target_paths_overwritten: "{{ [_default] | product(_target_paths) | map('combine') }}"
        _basename: "ansible.builtin.basename"
        _dirname: "ansible.builtin.dirname"
        _results: "{{ _r2_objects_query.results | default([]) }}"
        _objects: "{{ _results | map(attribute='s3_keys') | flatten }}"

    - name: Debug target R2 objects
      ansible.builtin.debug:
        msg: "{{ _r2_target_objects }}"

    - name: Debug existing R2 objects
      ansible.builtin.debug:
        msg: "{{ _r2_existing_objects }}"

    - name: Debug target R2 paths
      ansible.builtin.debug:
        msg: "{{ _r2_target_paths }}"

    - name: Debug existing R2 paths
      ansible.builtin.debug:
        msg: "{{ _r2_existing_paths }}"

    - name: Verify pokerops.r2.sync playbook tasks
      ansible.builtin.assert:
        that:
          - _r2_target_objects | reject('in', _r2_existing_objects) | length == 0
          - _r2_target_paths | rejectattr('remote', 'in', _r2_existing_paths) | length == 0
