---
name: molecule

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

on:
  pull_request:
    branches:
      - master
    paths:
      - "molecule/**"
      - "playbooks/**"
      - "requirements.yml"
      - "Makefile"
      - "pyproject.toml"
      - "poetry.lock"
      - "devbox.json"
      - "devbox.lock"
      - .github/workflows/molecule.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - create
          - sync
        image:
          - name: ubuntu2204
            command: /lib/systemd/systemd
          - name: debian12
            command: /lib/systemd/systemd
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: "pokerops.r2"

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          enable-cache: true

      - name: Run molecule tests.
        run: devbox run make test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DOCKER_IMAGE: ${{ matrix.image.name }}
          MOLECULE_DOCKER_COMMAND: ${{ matrix.image.command }}
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
